### ISSUE TITLE
Archlinux pacman 无法安装软件包

### ISSUE THREAD

**Issue by shuangsilab** [Moe-hacker/termux-container#1]
如题。错误信息如下
[root@arch ~]# pacman -Syu                              
:: Synchronizing package databases...
 core                  199.1 KiB  60.2 KiB/s 00:03 100% 
 extra                   2.3 MiB  2.51 MiB/s 00:01 100%
 community         5.4 MiB  6.59 MiB/s 00:01 100% 
 alarm                  55.5 KiB  31.5 KiB/s 00:02 100% 
 aur is up to date                                      
:: Starting full system upgrade...                      
resolving dependencies...                               
looking for conflicting packages...
                                                                             
Packages (1) device-mapper-2.03.13-1
                                                                            
Total Download Size:   0.26 MiB
Total Installed Size:  0.85 MiB                         
Net Upgrade Size:      0.00 MiB                                                                                 
:: Proceed with installation? [Y/n] Y
error: could not determine cachedir mount point /var/cache/pacman/pkg
error: failed to commit transaction (not enough free disk space)                                                
Errors occurred, no packages were upgraded.
但是在chroot环境里输入mount --rbind / / 就能解决问题，不知道原因是什么，能帮忙看一下么

**Comment by Moe-hacker** [comment]
谢邀，年轻人的第一条issue
刚说收官就看到一条issue[受虐滑稽]
Arch wiki上说过，"这通常是由于进入 chroot 时 chroot 目录不是挂载点造成的"
于是我在脚本中写了，当使用目录安装时：
mount --bind ${CHROOT_DIR} ${CHROOT_DIR} >/dev/null 2>&1
这样就把chroot目录挂载到了自身，
但是看结果貌似并没有起作用。
经过一番百度&测试，我把--bind改为--rbind貌似起了作用，我用目录安装测试的，不知你是否使用了镜像？
