### ISSUE TITLE
未连接到pulseaudio服务

### ISSUE THREAD

**Issue by Muki-naa** [Moe-hacker/termux-container#2]
我使用了你的镜像，但是在我运行并打开vnc之后，我发现无法使用声音，显示“未连接带pulseaudio服务”请问他是如何工作的。
我曾使用原生termux开启pulseaudio来连接，使用paplay --server 127.0.0.1 1.wav可以正常发声，但在镜像中开启网页无法发出声音。

**Comment by Moe-hacker** [comment]
不知是否因为之前用过隔壁大佬的tmoe脚本，我在termux中执行pulseaudio --start是可以连上声音的，但是貌似音质并不咋样，看视频还是推荐直接用电脑😃
对了，我这边执行paplay --server 127.0.0.1 1.wav会报错。
