### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 2096779623** [Moe-hacker/termux-container#7]
![image](https://user-images.githubusercontent.com/57583560/145812391-4deb1d91-d657-48c5-9b9b-67ee7ff7f44b.png)
![image](https://user-images.githubusercontent.com/57583560/145812404-27f57708-f8cd-47f6-9bd5-88471d6879b4.png)
![image](https://user-images.githubusercontent.com/57583560/145812411-5aa087ba-17a2-473d-855b-85d1647fcf25.png)
![image](https://user-images.githubusercontent.com/57583560/145812435-f9dead20-29cf-48e9-9098-027f4c79e020.png)
这是我在运行过程中出现的Bug，但是在shell直接运行不会报错：
![image](https://user-images.githubusercontent.com/57583560/145812479-5760f557-4c5f-4461-bc89-61b98dca9d51.png)

**Comment by Moe-hacker** [comment]
shell总会有奇奇怪怪的bug
建议先把翻译搞好
这东西我水了半年，建议仔细研究下，有些东西翻译就翻译全点😂

**Comment by 2096779623** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 2096779623** [comment]
> shell总会有奇奇怪怪的bug 建议先把翻译搞好 这东西我水了半年，建议仔细研究下，有些东西翻译就翻译全点😂

不就只有container没翻译吗
